name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Download and install JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz
   
    - name: Install JMeter Plugin Manager
      run: |
        curl -L https://jmeter-plugins.org/get/ -o plugins-manager.jar
        mv plugins-manager.jar apache-jmeter-5.6.3/lib/ext/

    - name: Move PluginsManagerCMD
      run: |
        mv PluginsManagerCMD.sh apache-jmeter-5.6.3/bin
       
        

    - name: Install JMeter Plugins
      run: |
        cd "apache-jmeter-5.6.3/bin"
        sudo PluginsManagerCMD.sh install \
          jpgc-tst=0.8 \
          jpgc-standard=1.4 \
          jpgc-graphs-basic=2.0 \
          jpgc-casutg=2.9
    
    - name: Run JMeter Test
      #if: always()
      run: |
        pwd
        ls
        ./apache-jmeter-5.6.3/bin/jmeter -n -t Gayan.jmx -l results.csv
    - name: Archive Jacoco reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: jmeter.log
