name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Download and install JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz
    - name: Install JMeter Plugins Manager
      run: |
            sudo wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar -P ./apache-jmeter-5.6.3/lib/
            sudo wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar -P ./apache-jmeter-5.6.3/lib/ext
            #cd "apache-jmeter-5.6.3/lib/"
            #ls
            sudo java -Djava.awt.headless=true $JVM_ARGS -jar ./apache-jmeter-5.6.3/lib/cmdrunner-2.3.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-casutg
            #sudo ./apache-jmeter-5.6.3/bin/PluginsManagerCMD.sh install jpgc-casutg
    - name: Run JMeter Test
      #if: always()
      run: |
        pwd
        ls
        sudo ./apache-jmeter-5.6.3/bin/jmeter -n -t Gayan.jmx -l results.csv
    - name: Archive Jacoco reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: results.csv
