name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Download and install JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz
   
    - name: Install JMeter Plugin Manager
      run: |
        curl -L https://jmeter-plugins.org/get/ -o plugins-manager.jar
        mv plugins-manager.jar apache-jmeter-5.6.3/lib/ext/
        sudo java -cp ./apache-jmeter-5.6.3/lib/ext/plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

    - name: Move PluginsManagerCMD
      run: |
        mv ./PluginsManagerCMD.sh apache-jmeter-5.6.3/bin
        chmod +x ./apache-jmeter-5.6.3/bin/PluginsManagerCMD.sh
       
        

    - name: Install JMeter Plugins
      run: |
        cd "apache-jmeter-5.6.3/lib"
        ls
        java -Djava.awt.headless=true $JVM_ARGS -jar cmdrunner-2.3.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-casutg 
    
    - name: Run JMeter Test
      #if: always()
      run: |
        pwd
        ls
        ./apache-jmeter-5.6.3/bin/jmeter -n -t Gayan.jmx -l results.csv
    - name: Archive Jacoco reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: jmeter.log
